[package]
name = "hextoast/fusion-rodux"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@^0.0.1-beta"
Rodux = "roblox/rodux@^3.0.0"